### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by iOS-Propelit** [heremaps/msdkui-ios#125]
I tried compiling the demo project and it threw me this error.

Please can anyone help me out with this.

![Screen Shot 2019-04-15 at 1 18 58 PM](https://user-images.githubusercontent.com/49634886/56118888-88fd3f80-5f88-11e9-9d7a-f297f077bc5c.png)

**Comment by datasun** [comment]
Usually this error comes up, when you are executing from the wrong folder. Can you more precisely describe the steps you did? Try to follow [these instructions](https://github.com/heremaps/msdkui-ios/blob/master/Documentation/Guides/ContributionGuide.md#building-the-demo-app).

**Comment by iOS-Propelit** [comment]
Ok I see that I don't have Mojave and Xcode 10.2. So is it mandatory, wouldn't it be compatible with Xcode 10.1?

**Comment by datasun** [comment]
Yes, unfortunately you need Swift 5.0 and Xcode 10.2, which requires you to upgrade to Mojave. Xcode 10.1 will not work. See also [here](https://github.com/heremaps/msdkui-ios#ios-environment). Of course, we would like to support older versions, but apparently this is not possible without forking.

**Comment by iOS-Propelit** [comment]
ok, ok thank you appreciate your help.

**Comment by guidove** [comment]
I know this issue is closed, but recently ran into the same problem with Xcode 12.4 (running on M1 Mac). Worked around it as follows:
- Go to Target MSDKUI_Demo > Build Phases. 
- Expand 'Adapt to Build Platform'
- Comment out the line 'git checkout $PROJECT_DIR/Commons/Info.plist' (place # in front of it)
- add line after this line (before fi) containing '(exit 0)' 

I'm not sure following is necessary, but I also commented out that line in the 'Revert changed from 'Adapt to Build Platform' ' section

Hope this helps someone

**Comment by datasun** [comment]
Thanks a lot, @guidove!
