### ISSUE TITLE
Create MSDKUI.framework for objective-c language

### ISSUE THREAD

**Issue by VivekVithlani** [heremaps/msdkui-ios#81]
Hello,

I have created project in **objective-c** language.
I created **MSDKUI.framework** as per documented.
But unfortunately this **MSDKUI.framework** working only in swift language.

If any way to create **MSDKUI.framework** and computable for **objective-c** language.

Thank you,
Vivek Vithalani.

**Comment by datasun** [comment]
Unfortunately the MSDKUI framework supports only Swift. However, since you can mix Objective-C apps with Swift code, you should be able access the MSDKUI components from a Swift bridge in your project.

**Comment by VivekVithlani** [comment]
I don't want to mix swift and objective-c, I contact to here map and here map will suggest to me please follow this steps and build **'MSDKUI.framework**' thats why I post this issue.

till date here map provided '**MSDKUI.framework**' for objective-c and that is working fine for me in xcode 9, But when I update iOS and xcode9 to xcode10 then provided framework was not work, app crashed every time.

If you know objective-c '**MSDKUI.framework**', please let me know.

Thank you,
Vivek Vithalani.

**Comment by datasun** [comment]
Thanks for your reply. Yes, that's true. Xcode 9 is no longer supported on the master branch. MSDKUI 1.3.1 was the last release to support Objective-C and it was dropped for the subsequent releases. However, it was never made available on GitHub. I think you could still get that release from your HERE representative. Since the project has become open-source it would be great to see an Objective-C fork. However, so far there was no demand for it as most developers seem to prefer Swift these days.
